-- The highlight groups map

local M = {}

---@param c table palette, keyed by role
---@param o table resolved options
function M.get(c, o)
  local bold = o.bold
  local italic = o.italic
  local undercurl = o.undercurl

  local groups = {
    -- Editor
    -- Absent on purpose (linked):
    -- CursorIM, LineNrAbove, LineNrBelow, FoldColumn, Whitespace, VertSplit,
    -- VisualNOS, TabLine.
    Normal = { fg = c.text, bg = c.bg },
    NormalNC = { fg = c.text, bg = c.bg },
    NormalFloat = { fg = c.text, bg = c.bg_float },
    FloatBorder = { fg = c.border, bg = c.bg_float },
    FloatTitle = { fg = c.title, bg = c.bg_float, bold = bold },
    FloatFooter = { fg = c.comment, bg = c.bg_float },
    ColorColumn = { bg = c.bg_alt },
    Conceal = { fg = c.lnr },
    Cursor = { fg = c.bg, bg = c.text },
    lCursor = { fg = c.bg, bg = c.text },
    TermCursor = { fg = c.bg, bg = c.accent },
    CursorColumn = { bg = c.bg_alt },
    CursorLine = { bg = c.bg_alt },
    CursorLineNr = { fg = c.lnr_cur, bold = bold },
    LineNr = { fg = c.lnr },
    SignColumn = { fg = c.lnr, bg = c.bg },
    Folded = { fg = c.op, bg = c.bg_float },
    Directory = { fg = c.dir, bold = bold },
    EndOfBuffer = { fg = c.bg },
    NonText = { fg = c.nontext },
    SpecialKey = { fg = c.op },
    MatchParen = { fg = c.text, bg = c.bg_hl, bold = bold },
    ModeMsg = { fg = c.dim, bold = bold },
    MoreMsg = { fg = c.hint },
    Question = { fg = c.hint },
    ErrorMsg = { fg = c.err, bold = bold },
    WarningMsg = { fg = c.warn },
    MsgArea = { fg = c.text },
    MsgSeparator = { fg = c.border, bg = c.bg_float },
    Title = { fg = c.title, bold = bold },
    WinSeparator = { fg = c.border },
    Visual = { bg = c.bg_sel },
    Search = { fg = c.text, bg = c.bg_search },
    IncSearch = { fg = c.bg, bg = c.accent, bold = bold },
    CurSearch = { fg = c.bg, bg = c.cursearch, bold = bold },
    Substitute = { fg = c.bg, bg = c.subst },
    QuickFixLine = { bg = c.bg_sel, bold = bold },
    Pmenu = { fg = c.text, bg = c.bg_float },
    PmenuSel = { fg = c.text, bg = c.bg_hl, bold = bold },
    PmenuKind = { fg = c.typ, bg = c.bg_float },
    PmenuKindSel = { fg = c.typ, bg = c.bg_hl },
    PmenuExtra = { fg = c.comment, bg = c.bg_float },
    PmenuExtraSel = { fg = c.dim, bg = c.bg_hl },
    PmenuSbar = { bg = c.bg_float },
    PmenuThumb = { bg = c.border },
    PmenuMatch = { fg = c.match, bg = c.bg_float, bold = bold },
    PmenuMatchSel = { fg = c.match, bg = c.bg_hl, bold = bold },
    WildMenu = { fg = c.bg, bg = c.accent },
    StatusLine = { fg = c.dim, bg = c.bg_float },
    StatusLineNC = { fg = c.comment, bg = c.bg_alt },
    TabLineFill = { bg = c.bg },
    TabLineSel = { fg = c.text, bg = c.bg_sel, bold = bold },
    WinBar = { fg = c.dim, bold = bold },
    WinBarNC = { fg = c.comment },
    Underlined = { underline = true },
    Ignore = { fg = c.lnr },
    Error = { fg = c.err },
    Todo = { fg = c.bg, bg = c.warn, bold = bold },

    -- Diff and spelling
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { bg = c.diff_text },
    Added = { fg = c.ok },
    Changed = { fg = c.info },
    Removed = { fg = c.err },
    SpellBad = { sp = c.err, underline = not undercurl, undercurl = undercurl },
    SpellCap = { sp = c.info, underline = not undercurl, undercurl = undercurl },
    SpellLocal = { sp = c.hint, underline = not undercurl, undercurl = undercurl },
    SpellRare = { sp = c.esc, underline = not undercurl, undercurl = undercurl },

    -- Debugger
    -- Both are hardcoded to a flat blue and red that follow nothing, so unlike
    -- most of this file these override a color rather than a link.
    debugPC = { bg = c.diff_change },
    debugBreakpoint = { fg = c.err },

    -- Legacy syntax (fallback for anything without a treesitter)
    Comment = { fg = c.comment, italic = italic },
    Constant = { fg = c.num },
    String = { fg = c.str },
    Character = { fg = c.str },
    Identifier = { fg = c.text },
    Function = { fg = c.func, bold = bold },
    Statement = { fg = c.kw, bold = bold },
    Label = { fg = c.label },
    Operator = { fg = c.op },
    PreProc = { fg = c.macro },
    Type = { fg = c.typ },
    Special = { fg = c.esc },
    Delimiter = { fg = c.punct },
    SpecialComment = { fg = c.str, italic = italic },
    Debug = { fg = c.warn },

    -- Treesitter
    -- Absent on purpose: @comment, @constant, @string, @character, @boolean,
    -- @number, @number.float, @function, @keyword, @type, @label, @operator,
    -- @attribute, @character.special, @string.special and @string.regexp.
    ["@variable"] = { fg = c.text },
    ["@variable.builtin"] = { fg = c.prop, italic = italic },
    ["@variable.parameter"] = { fg = c.prop },
    ["@variable.parameter.builtin"] = { fg = c.prop, italic = italic },
    ["@variable.member"] = { fg = c.prop },
    ["@constant.builtin"] = { fg = c.num, italic = italic },
    ["@constant.macro"] = { fg = c.macro },
    ["@module"] = { fg = c.mod },
    ["@module.builtin"] = { fg = c.mod, italic = italic },
    ["@string.documentation"] = { fg = c.str, italic = italic },
    ["@string.escape"] = { fg = c.esc, bold = bold },
    ["@string.special.symbol"] = { fg = c.esc },
    ["@string.special.path"] = { fg = c.str, underline = true },
    ["@string.special.url"] = { fg = c.str, underline = true },
    ["@type.builtin"] = { fg = c.typ, italic = italic },
    ["@type.definition"] = { fg = c.typ, bold = bold },
    ["@attribute.builtin"] = { fg = c.macro, italic = italic },
    ["@property"] = { fg = c.prop },
    ["@function.builtin"] = { fg = c.func, italic = italic },
    ["@function.call"] = { fg = c.func },
    ["@function.macro"] = { fg = c.macro },
    ["@function.method"] = { fg = c.func, bold = bold },
    ["@function.method.call"] = { fg = c.func },
    ["@constructor"] = { fg = c.typ },
    ["@keyword.coroutine"] = { fg = c.kw, bold = bold },
    ["@keyword.function"] = { fg = c.kw, bold = bold },
    ["@keyword.operator"] = { fg = c.op, bold = bold },
    ["@keyword.import"] = { fg = c.macro },
    ["@keyword.type"] = { fg = c.typ, bold = bold },
    ["@keyword.modifier"] = { fg = c.kw },
    ["@keyword.repeat"] = { fg = c.kw, bold = bold },
    ["@keyword.return"] = { fg = c.kw, bold = bold },
    ["@keyword.debug"] = { fg = c.warn, bold = bold },
    ["@keyword.exception"] = { fg = c.kw, bold = bold },
    ["@keyword.conditional"] = { fg = c.kw, bold = bold },
    ["@keyword.conditional.ternary"] = { fg = c.op },
    ["@keyword.directive"] = { fg = c.macro },
    ["@keyword.directive.define"] = { fg = c.macro },
    ["@punctuation.delimiter"] = { fg = c.punct },
    ["@punctuation.bracket"] = { fg = c.punct },
    ["@punctuation.special"] = { fg = c.op },
    ["@comment.documentation"] = { fg = c.comment, italic = italic },
    ["@comment.error"] = { fg = c.bg, bg = c.err, bold = bold },
    ["@comment.warning"] = { fg = c.bg, bg = c.warn, bold = bold },
    ["@comment.todo"] = { fg = c.bg, bg = c.hint, bold = bold },
    ["@comment.note"] = { fg = c.bg, bg = c.info, bold = bold },
    ["@markup"] = { fg = c.text },
    ["@markup.strong"] = { fg = c.text, bold = true },
    ["@markup.italic"] = { fg = c.text, italic = true },
    ["@markup.strikethrough"] = { fg = c.comment, strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.h1, bold = bold },
    ["@markup.heading.1"] = { fg = c.h1, bold = bold },
    ["@markup.heading.2"] = { fg = c.h2, bold = bold },
    ["@markup.heading.3"] = { fg = c.h3, bold = bold },
    ["@markup.heading.4"] = { fg = c.h4, bold = bold },
    ["@markup.heading.5"] = { fg = c.h5, bold = bold },
    ["@markup.heading.6"] = { fg = c.h6, bold = bold },
    ["@markup.quote"] = { fg = c.comment, italic = italic },
    ["@markup.math"] = { fg = c.str },
    ["@markup.link"] = { fg = c.str },
    ["@markup.link.label"] = { fg = c.esc },
    ["@markup.link.url"] = { fg = c.str, underline = true },
    ["@markup.raw"] = { fg = c.str },
    ["@markup.raw.block"] = { fg = c.str },
    ["@markup.list"] = { fg = c.op },
    ["@markup.list.checked"] = { fg = c.ok },
    ["@markup.list.unchecked"] = { fg = c.lnr },
    ["@diff.plus"] = { fg = c.ok, bg = c.diff_add },
    ["@diff.minus"] = { fg = c.err, bg = c.diff_delete },
    ["@diff.delta"] = { fg = c.info, bg = c.diff_change },
    ["@tag"] = { fg = c.tag },
    ["@tag.builtin"] = { fg = c.tag, italic = italic },
    ["@tag.attribute"] = { fg = c.prop },
    ["@tag.delimiter"] = { fg = c.punct },
    ["@none"] = {},

    -- LSP
    -- Comments arrive from servers with the whole comment as one token, which
    -- flattens whatever treesitter found inside it -- todo markers, doc tags. An
    -- empty table turns the semantic token off and lets the parser keep it.
    ["@lsp.type.comment"] = {},
    ["@lsp.type.modifier"] = { link = "@keyword.modifier" },
    ["@lsp.mod.readonly"] = { link = "@constant" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    LspReferenceWrite = { bg = c.bg_sel, underline = true },
    LspInlayHint = { fg = c.lnr, bg = c.bg_alt, italic = italic },
    LspCodeLens = { fg = c.comment, italic = italic },
    LspCodeLensSeparator = { fg = c.lnr },
    LspSignatureActiveParameter = { fg = c.prop, bg = c.bg_sel, bold = bold },

    -- Diagnostics
    DiagnosticError = { fg = c.err },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.ok },
    DiagnosticVirtualTextError = { fg = c.err, bg = c.vt_error },
    DiagnosticVirtualTextWarn = { fg = c.warn, bg = c.vt_warn },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.vt_info },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.vt_hint },
    DiagnosticVirtualTextOk = { fg = c.ok, bg = c.diff_add },
    DiagnosticVirtualLinesError = { fg = c.err, bg = c.vt_error },
    DiagnosticVirtualLinesWarn = { fg = c.warn, bg = c.vt_warn },
    DiagnosticVirtualLinesInfo = { fg = c.info, bg = c.vt_info },
    DiagnosticVirtualLinesHint = { fg = c.hint, bg = c.vt_hint },
    DiagnosticVirtualLinesOk = { fg = c.ok, bg = c.diff_add },
    DiagnosticUnderlineError = { sp = c.err, underline = not undercurl, undercurl = undercurl },
    DiagnosticUnderlineWarn = { sp = c.warn, underline = not undercurl, undercurl = undercurl },
    DiagnosticUnderlineInfo = { sp = c.info, underline = not undercurl, undercurl = undercurl },
    DiagnosticUnderlineHint = { sp = c.hint, underline = not undercurl, undercurl = undercurl },
    DiagnosticUnderlineOk = { sp = c.ok, underline = not undercurl, undercurl = undercurl },
    DiagnosticFloatingError = { fg = c.err, bg = c.bg_float },
    DiagnosticFloatingWarn = { fg = c.warn, bg = c.bg_float },
    DiagnosticFloatingInfo = { fg = c.info, bg = c.bg_float },
    DiagnosticFloatingHint = { fg = c.hint, bg = c.bg_float },
    DiagnosticFloatingOk = { fg = c.ok, bg = c.bg_float },
    DiagnosticSignError = { fg = c.err, bg = c.bg },
    DiagnosticSignWarn = { fg = c.warn, bg = c.bg },
    DiagnosticSignInfo = { fg = c.info, bg = c.bg },
    DiagnosticSignHint = { fg = c.hint, bg = c.bg },
    DiagnosticSignOk = { fg = c.ok, bg = c.bg },
    DiagnosticDeprecated = { sp = c.comment, strikethrough = true },
    DiagnosticUnnecessary = { fg = c.lnr },
  }

  -- Transparency clears the editor background and leaves floats,
  -- selections and diff backdrops alone: a float with no
  -- background of its own is unreadable over arbitrary content.
  if o.transparent then
    for _, spec in pairs(groups) do
      if spec.bg == c.bg then
        spec.bg = "NONE"
      end
    end
  end

  return groups
end

return M
