-- observatory.nvim -- what each scheme is, measured
--
-- Generated alongside the palettes. `family` is the subject, `method`
-- how its colors were arrived at -- "sampled" from a published image,
-- "computed" from a measured quantity, "solved" from the separation
-- constraints alone. `span` is the width in degrees of hue its accents
-- occupy, `floor` the smallest CIE76 distance between any two of its
-- syntax colors, and `chroma` their mean saturation in Lab terms.
-- Sort or filter on any of them.

return {
  {
    name = "observatory-aurora",
    about = "the green aurora, on its own night sky",
    family = "sky",
    method = "computed",
    floor = 12.5,
    accents = 9,
    span = 200,
    chroma = 53.1,
    text_cr = 15.40,
    top_cr = 11.80,
    warm = 1,
  },
  {
    name = "observatory-aurora-red",
    about = "the rare all-red aurora, green demoted to an accent",
    family = "sky",
    method = "computed",
    floor = 12.0,
    accents = 8,
    span = 232,
    chroma = 44.2,
    text_cr = 15.44,
    top_cr = 11.84,
    warm = 5,
  },
  {
    name = "observatory-comet",
    about = "two tails, two hue families, nothing in between",
    family = "sky",
    method = "computed",
    floor = 10.7,
    accents = 7,
    span = 197,
    chroma = 50.9,
    text_cr = 15.40,
    top_cr = 12.19,
    warm = 2,
  },
  {
    name = "observatory-eclipse",
    about = "the corona, almost colorless, with one ruby line",
    family = "sky",
    method = "computed",
    floor = 11.4,
    accents = 8,
    span = 194,
    chroma = 27.1,
    text_cr = 10.56,
    top_cr = 15.24,
    warm = 5,
  },
  {
    name = "observatory-hubble",
    about = "the Hubble palette, which lands on the corners of the RGB cube",
    family = "sky",
    method = "computed",
    floor = 13.5,
    accents = 8,
    span = 300,
    chroma = 60.4,
    text_cr = 15.36,
    top_cr = 12.01,
    warm = 1,
  },
  {
    name = "observatory-nacreous",
    about = "iridescent ice at 20 km, and the only pastel here",
    family = "sky",
    method = "computed",
    floor = 12.4,
    accents = 6,
    span = 229,
    chroma = 16.6,
    text_cr = 14.57,
    top_cr = 16.92,
    warm = 2,
  },
  {
    name = "observatory-nightsky",
    about = "star colors by spectral class, on a deep blue sky",
    family = "sky",
    method = "computed",
    floor = 10.7,
    accents = 7,
    span = 170,
    chroma = 20.6,
    text_cr = 10.58,
    top_cr = 15.33,
    warm = 4,
  },
  {
    name = "observatory-noctilucent",
    about = "sunlight that has already gone below the horizon, seen from 83 km",
    family = "sky",
    method = "computed",
    floor = 21.3,
    accents = 6,
    span = 204,
    chroma = 47.1,
    text_cr = 11.98,
    top_cr = 14.48,
    warm = 2,
  },
  {
    name = "observatory-mercury",
    about = "the enhanced-color globe: tan crust, blue minerals, gold plains",
    family = "solar",
    method = "sampled",
    floor = 9.5,
    accents = 8,
    span = 234,
    chroma = 33.6,
    text_cr = 12.46,
    top_cr = 16.90,
    warm = 4,
  },
  {
    name = "observatory-mercury-computed",
    about = "the grayest planet, mapped by reflectance unit",
    family = "solar",
    method = "computed",
    floor = 11.3,
    accents = 8,
    span = 197,
    chroma = 28.2,
    text_cr = 12.66,
    top_cr = 16.94,
    warm = 3,
  },
  {
    name = "observatory-venus",
    about = "cream cloud in every direction, and nothing else",
    family = "solar",
    method = "sampled",
    floor = 10.1,
    accents = 4,
    span = 170,
    chroma = 7.7,
    text_cr = 9.97,
    top_cr = 16.93,
    warm = 3,
  },
  {
    name = "observatory-venus-computed",
    about = "the cloud deck above, the surface nobody sees below",
    family = "solar",
    method = "computed",
    floor = 15.5,
    accents = 8,
    span = 143,
    chroma = 33.4,
    text_cr = 13.10,
    top_cr = 15.77,
    warm = 7,
  },
  {
    name = "observatory-earth",
    about = "ocean, vegetation, desert, ice",
    family = "solar",
    method = "sampled",
    floor = 9.6,
    accents = 6,
    span = 182,
    chroma = 44.6,
    text_cr = 12.32,
    top_cr = 16.87,
    warm = 2,
  },
  {
    name = "observatory-earth-computed",
    about = "the only world that needs no help finding colors",
    family = "solar",
    method = "computed",
    floor = 11.6,
    accents = 9,
    span = 196,
    chroma = 40.3,
    text_cr = 12.40,
    top_cr = 16.93,
    warm = 2,
  },
  {
    name = "observatory-luna",
    about = "the full moon: five grays and a warm cast",
    family = "solar",
    method = "sampled",
    floor = 11.1,
    accents = 4,
    span = 60,
    chroma = 7.5,
    text_cr = 12.47,
    top_cr = 16.85,
    warm = 3,
  },
  {
    name = "observatory-luna-computed",
    about = "gray, until you stretch it",
    family = "solar",
    method = "computed",
    floor = 12.0,
    accents = 8,
    span = 198,
    chroma = 21.8,
    text_cr = 12.39,
    top_cr = 16.93,
    warm = 4,
  },
  {
    name = "observatory-mars",
    about = "rust, dust and one bright polar cap",
    family = "solar",
    method = "sampled",
    floor = 16.5,
    accents = 5,
    span = 177,
    chroma = 28.1,
    text_cr = 12.10,
    top_cr = 16.93,
    warm = 4,
  },
  {
    name = "observatory-mars-computed",
    about = "rust, with the blue its sunsets actually are",
    family = "solar",
    method = "computed",
    floor = 14.4,
    accents = 8,
    span = 205,
    chroma = 27.0,
    text_cr = 12.40,
    top_cr = 16.85,
    warm = 4,
  },
  {
    name = "observatory-jupiter",
    about = "zones, belts and the Great Red Spot",
    family = "solar",
    method = "sampled",
    floor = 17.3,
    accents = 5,
    span = 185,
    chroma = 41.2,
    text_cr = 13.53,
    top_cr = 14.76,
    warm = 4,
  },
  {
    name = "observatory-jupiter-computed",
    about = "zones, belts, the red spot and the blue poles",
    family = "solar",
    method = "computed",
    floor = 12.0,
    accents = 8,
    span = 186,
    chroma = 28.4,
    text_cr = 12.50,
    top_cr = 16.85,
    warm = 6,
  },
  {
    name = "observatory-io",
    about = "sulfur, ochre and frost, and no blue anywhere",
    family = "solar",
    method = "sampled",
    floor = 17.7,
    accents = 6,
    span = 18,
    chroma = 38.9,
    text_cr = 13.61,
    top_cr = 16.85,
    warm = 6,
  },
  {
    name = "observatory-io-computed",
    about = "sulfur yellow, with frost as the only cool thing on it",
    family = "solar",
    method = "computed",
    floor = 11.5,
    accents = 7,
    span = 193,
    chroma = 50.5,
    text_cr = 15.44,
    top_cr = 14.23,
    warm = 5,
  },
  {
    name = "observatory-europa",
    about = "ice, and the rust-brown cracks across it",
    family = "solar",
    method = "sampled",
    floor = 17.2,
    accents = 5,
    span = 44,
    chroma = 29.0,
    text_cr = 12.61,
    top_cr = 16.89,
    warm = 4,
  },
  {
    name = "observatory-europa-computed",
    about = "water ice, and whatever the ocean brought up",
    family = "solar",
    method = "computed",
    floor = 11.0,
    accents = 8,
    span = 194,
    chroma = 25.9,
    text_cr = 12.71,
    top_cr = 16.92,
    warm = 4,
  },
  {
    name = "observatory-ganymede",
    about = "grooved terrain in tan, and the frost at its poles",
    family = "solar",
    method = "sampled",
    floor = 16.7,
    accents = 4,
    span = 16,
    chroma = 31.5,
    text_cr = 13.10,
    top_cr = 16.91,
    warm = 4,
  },
  {
    name = "observatory-ganymede-computed",
    about = "grooved ice over ancient rock",
    family = "solar",
    method = "computed",
    floor = 14.3,
    accents = 8,
    span = 190,
    chroma = 26.9,
    text_cr = 11.32,
    top_cr = 16.80,
    warm = 3,
  },
  {
    name = "observatory-callisto",
    about = "the most cratered surface known, in dark tan",
    family = "solar",
    method = "sampled",
    floor = 18.5,
    accents = 6,
    span = 156,
    chroma = 26.0,
    text_cr = 13.67,
    top_cr = 16.96,
    warm = 3,
  },
  {
    name = "observatory-callisto-computed",
    about = "the oldest surface, and the least to say about it",
    family = "solar",
    method = "computed",
    floor = 17.5,
    accents = 6,
    span = 188,
    chroma = 27.8,
    text_cr = 10.41,
    top_cr = 17.00,
    warm = 3,
  },
  {
    name = "observatory-saturn",
    about = "pale gold, with the rings' shadow laid across it",
    family = "solar",
    method = "sampled",
    floor = 17.2,
    accents = 4,
    span = 12,
    chroma = 33.4,
    text_cr = 12.93,
    top_cr = 17.04,
    warm = 4,
  },
  {
    name = "observatory-saturn-computed",
    about = "butterscotch, with the blue winter hemisphere",
    family = "solar",
    method = "computed",
    floor = 11.8,
    accents = 8,
    span = 196,
    chroma = 32.8,
    text_cr = 12.57,
    top_cr = 16.94,
    warm = 6,
  },
  {
    name = "observatory-titan",
    about = "a hazy orange orb, which is all anyone sees from outside",
    family = "solar",
    method = "sampled",
    floor = 16.9,
    accents = 4,
    span = 142,
    chroma = 29.8,
    text_cr = 12.83,
    top_cr = 16.87,
    warm = 3,
  },
  {
    name = "observatory-titan-computed",
    about = "an orange monochrome; the haze admits nothing else",
    family = "solar",
    method = "computed",
    floor = 10.7,
    accents = 7,
    span = 31,
    chroma = 46.8,
    text_cr = 11.60,
    top_cr = 15.01,
    warm = 7,
  },
  {
    name = "observatory-enceladus",
    about = "white ice, and the fractures that vent it",
    family = "solar",
    method = "sampled",
    floor = 11.6,
    accents = 4,
    span = 195,
    chroma = 8.4,
    text_cr = 12.32,
    top_cr = 16.86,
    warm = 1,
  },
  {
    name = "observatory-enceladus-computed",
    about = "the brightest surface in the solar system",
    family = "solar",
    method = "computed",
    floor = 14.1,
    accents = 8,
    span = 28,
    chroma = 20.0,
    text_cr = 12.20,
    top_cr = 16.86,
    warm = 0,
  },
  {
    name = "observatory-iapetus",
    about = "two-tone: snow on one face, tar on the other",
    family = "solar",
    method = "sampled",
    floor = 17.1,
    accents = 6,
    span = 141,
    chroma = 46.3,
    text_cr = 12.96,
    top_cr = 15.08,
    warm = 4,
  },
  {
    name = "observatory-iapetus-computed",
    about = "two hemispheres, and nothing in between",
    family = "solar",
    method = "computed",
    floor = 15.2,
    accents = 7,
    span = 198,
    chroma = 31.6,
    text_cr = 11.09,
    top_cr = 16.92,
    warm = 4,
  },
  {
    name = "observatory-uranus",
    about = "featureless pale cyan, and that is the observation",
    family = "solar",
    method = "sampled",
    floor = 16.2,
    accents = 4,
    span = 40,
    chroma = 23.0,
    text_cr = 12.43,
    top_cr = 16.90,
    warm = 0,
  },
  {
    name = "observatory-uranus-computed",
    about = "the most featureless palette here, and honestly so",
    family = "solar",
    method = "computed",
    floor = 13.2,
    accents = 7,
    span = 14,
    chroma = 23.2,
    text_cr = 12.29,
    top_cr = 16.85,
    warm = 0,
  },
  {
    name = "observatory-neptune",
    about = "azure, a shade deeper than Uranus and no bluer",
    family = "solar",
    method = "sampled",
    floor = 10.4,
    accents = 4,
    span = 3,
    chroma = 25.0,
    text_cr = 12.32,
    top_cr = 16.88,
    warm = 0,
  },
  {
    name = "observatory-neptune-computed",
    about = "the iconic blue, which is not quite the real one",
    family = "solar",
    method = "computed",
    floor = 11.4,
    accents = 8,
    span = 54,
    chroma = 28.0,
    text_cr = 12.53,
    top_cr = 16.89,
    warm = 0,
  },
  {
    name = "observatory-triton",
    about = "cantaloupe terrain under a pink nitrogen cap",
    family = "solar",
    method = "sampled",
    floor = 8.5,
    accents = 4,
    span = 169,
    chroma = 8.9,
    text_cr = 12.40,
    top_cr = 16.92,
    warm = 1,
  },
  {
    name = "observatory-triton-computed",
    about = "cantaloupe terrain and pink nitrogen frost",
    family = "solar",
    method = "computed",
    floor = 12.9,
    accents = 8,
    span = 176,
    chroma = 22.6,
    text_cr = 12.49,
    top_cr = 16.88,
    warm = 5,
  },
  {
    name = "observatory-pluto",
    about = "the heart, in cream and tholin tan",
    family = "solar",
    method = "sampled",
    floor = 18.1,
    accents = 4,
    span = 4,
    chroma = 36.6,
    text_cr = 13.63,
    top_cr = 16.87,
    warm = 4,
  },
  {
    name = "observatory-pluto-computed",
    about = "nitrogen ice, tholin red, and a blue sky",
    family = "solar",
    method = "computed",
    floor = 16.2,
    accents = 8,
    span = 192,
    chroma = 27.8,
    text_cr = 11.34,
    top_cr = 16.96,
    warm = 5,
  },
  {
    name = "observatory-charon",
    about = "gray ice, and one red-brown pole",
    family = "solar",
    method = "sampled",
    floor = 9.8,
    accents = 5,
    span = 162,
    chroma = 40.3,
    text_cr = 12.40,
    top_cr = 16.91,
    warm = 4,
  },
  {
    name = "observatory-charon-computed",
    about = "Pluto's tholins, arrived second-hand",
    family = "solar",
    method = "computed",
    floor = 14.7,
    accents = 8,
    span = 190,
    chroma = 25.7,
    text_cr = 11.25,
    top_cr = 16.93,
    warm = 2,
  },
  {
    name = "observatory-ceres",
    about = "blue-gray regolith around one bright crater",
    family = "solar",
    method = "sampled",
    floor = 15.8,
    accents = 4,
    span = 130,
    chroma = 25.2,
    text_cr = 11.96,
    top_cr = 16.98,
    warm = 1,
  },
  {
    name = "observatory-ceres-computed",
    about = "bright salt on a very dark world",
    family = "solar",
    method = "computed",
    floor = 18.0,
    accents = 8,
    span = 196,
    chroma = 29.7,
    text_cr = 11.65,
    top_cr = 16.91,
    warm = 5,
  },
  {
    name = "observatory-rings",
    about = "a scan across the annuli, unlit side",
    family = "solar",
    method = "sampled",
    floor = 18.2,
    accents = 4,
    span = 127,
    chroma = 25.8,
    text_cr = 13.52,
    top_cr = 16.95,
    warm = 3,
  },
  {
    name = "observatory-arrokoth",
    about = "the reddest thing photographed up close",
    family = "solar",
    method = "sampled",
    floor = 8.1,
    accents = 4,
    span = 3,
    chroma = 23.3,
    text_cr = 12.40,
    top_cr = 16.85,
    warm = 4,
  },
  {
    name = "observatory-albireo",
    about = "the color-contrast doubles, and the green that isn't",
    family = "star",
    method = "computed",
    floor = 18.8,
    accents = 7,
    span = 167,
    chroma = 35.5,
    text_cr = 11.05,
    top_cr = 14.23,
    warm = 4,
  },
  {
    name = "observatory-alphacentauri",
    about = "the nearest three stars, and one flare",
    family = "star",
    method = "computed",
    floor = 16.9,
    accents = 5,
    span = 168,
    chroma = 40.7,
    text_cr = 10.87,
    top_cr = 16.65,
    warm = 4,
  },
  {
    name = "observatory-betelgeuse",
    about = "a resolved supergiant, mid-dimming, in amber",
    family = "star",
    method = "sampled",
    floor = 9.8,
    accents = 7,
    span = 37,
    chroma = 38.8,
    text_cr = 12.40,
    top_cr = 16.89,
    warm = 7,
  },
  {
    name = "observatory-betelgeuse-computed",
    about = "a supergiant, and the dust that dimmed it",
    family = "star",
    method = "computed",
    floor = 17.8,
    accents = 6,
    span = 2,
    chroma = 48.0,
    text_cr = 10.87,
    top_cr = 16.94,
    warm = 6,
  },
  {
    name = "observatory-nervia",
    about = "the star Eburonia orbits, which is very nearly the Sun",
    family = "star",
    method = "sampled",
    floor = 17.0,
    accents = 5,
    span = 2,
    chroma = 36.8,
    text_cr = 12.57,
    top_cr = 16.82,
    warm = 5,
  },
  {
    name = "observatory-nervia-computed",
    about = "the star Eburonia orbits, by its own temperatures",
    family = "star",
    method = "computed",
    floor = 12.3,
    accents = 8,
    span = 97,
    chroma = 31.2,
    text_cr = 12.07,
    top_cr = 16.84,
    warm = 7,
  },
  {
    name = "observatory-carbon",
    about = "the reddest stars there are, in purity not hue",
    family = "star",
    method = "computed",
    floor = 16.5,
    accents = 6,
    span = 6,
    chroma = 53.5,
    text_cr = 11.86,
    top_cr = 16.52,
    warm = 6,
  },
  {
    name = "observatory-cepheid",
    about = "a light curve, and no color to speak of",
    family = "star",
    method = "computed",
    floor = 15.4,
    accents = 5,
    span = 3,
    chroma = 23.0,
    text_cr = 10.87,
    top_cr = 16.92,
    warm = 5,
  },
  {
    name = "observatory-etacarinae",
    about = "two lobes of debris from a star that survived its own explosion",
    family = "star",
    method = "sampled",
    floor = 16.1,
    accents = 6,
    span = 104,
    chroma = 36.6,
    text_cr = 12.35,
    top_cr = 15.58,
    warm = 5,
  },
  {
    name = "observatory-etacarinae-computed",
    about = "the Homunculus, and the star inside it",
    family = "star",
    method = "computed",
    floor = 20.7,
    accents = 7,
    span = 185,
    chroma = 33.5,
    text_cr = 11.26,
    top_cr = 15.66,
    warm = 6,
  },
  {
    name = "observatory-magnitude",
    about = "the eight brightest stars, with Vega at zero",
    family = "star",
    method = "computed",
    floor = 15.8,
    accents = 8,
    span = 171,
    chroma = 29.9,
    text_cr = 10.57,
    top_cr = 16.94,
    warm = 4,
  },
  {
    name = "observatory-sirius",
    about = "brighter is cooler, for once",
    family = "star",
    method = "computed",
    floor = 11.2,
    accents = 6,
    span = 3,
    chroma = 32.0,
    text_cr = 12.92,
    top_cr = 16.79,
    warm = 0,
  },
  {
    name = "observatory-v838monocerotis",
    about = "a light echo, which is not an explosion but its shadow on dust",
    family = "star",
    method = "sampled",
    floor = 16.9,
    accents = 8,
    span = 180,
    chroma = 31.7,
    text_cr = 12.43,
    top_cr = 17.01,
    warm = 4,
  },
  {
    name = "observatory-v838monocerotis-computed",
    about = "one flash, seen at four delays",
    family = "star",
    method = "computed",
    floor = 16.3,
    accents = 7,
    span = 192,
    chroma = 32.6,
    text_cr = 11.89,
    top_cr = 16.65,
    warm = 3,
  },
  {
    name = "observatory-boyajian",
    about = "a dip in a light curve, measured filter by filter",
    family = "star",
    method = "computed",
    floor = 18.7,
    accents = 5,
    span = 230,
    chroma = 44.0,
    text_cr = 11.67,
    top_cr = 13.77,
    warm = 2,
  },
  {
    name = "observatory-przybylski",
    about = "a spectrum full of elements that should not be there",
    family = "star",
    method = "computed",
    floor = 28.3,
    accents = 9,
    span = 282,
    chroma = 55.1,
    text_cr = 13.69,
    top_cr = 15.26,
    warm = 1,
  },
  {
    name = "observatory-ss433",
    about = "one line, two jets, and the half that is invisible",
    family = "star",
    method = "computed",
    floor = 21.3,
    accents = 7,
    span = 202,
    chroma = 33.5,
    text_cr = 13.01,
    top_cr = 15.98,
    warm = 5,
  },
  {
    name = "observatory-browndwarf",
    about = "not a star, not a planet: a red monochrome",
    family = "star",
    method = "sampled",
    floor = 15.8,
    accents = 7,
    span = 101,
    chroma = 28.8,
    text_cr = 11.92,
    top_cr = 16.95,
    warm = 6,
  },
  {
    name = "observatory-browndwarf-computed",
    about = "the failed stars, and the one honest purple here",
    family = "star",
    method = "computed",
    floor = 17.5,
    accents = 6,
    span = 145,
    chroma = 28.3,
    text_cr = 11.02,
    top_cr = 16.93,
    warm = 2,
  },
  {
    name = "observatory-wolfrayet",
    about = "a star shedding itself, in plum and steel",
    family = "star",
    method = "sampled",
    floor = 16.2,
    accents = 6,
    span = 144,
    chroma = 26.1,
    text_cr = 12.41,
    top_cr = 14.56,
    warm = 4,
  },
  {
    name = "observatory-wolfrayet-computed",
    about = "the hottest stars there are, and none of it is the continuum",
    family = "star",
    method = "computed",
    floor = 15.7,
    accents = 7,
    span = 225,
    chroma = 47.1,
    text_cr = 11.61,
    top_cr = 16.48,
    warm = 1,
  },
  {
    name = "observatory-crux",
    about = "the Southern Cross, which is three quarters one color",
    family = "star",
    method = "computed",
    floor = 20.5,
    accents = 5,
    span = 174,
    chroma = 31.8,
    text_cr = 10.43,
    top_cr = 15.50,
    warm = 3,
  },
  {
    name = "observatory-arcturus",
    about = "the reference K giant, and the gaps in its light",
    family = "star",
    method = "computed",
    floor = 17.5,
    accents = 8,
    span = 216,
    chroma = 42.0,
    text_cr = 10.63,
    top_cr = 16.91,
    warm = 5,
  },
  {
    name = "observatory-vega",
    about = "the star everything else is measured against",
    family = "star",
    method = "computed",
    floor = 17.1,
    accents = 6,
    span = 220,
    chroma = 47.4,
    text_cr = 10.96,
    top_cr = 16.94,
    warm = 2,
  },
  {
    name = "observatory-rigel",
    about = "a blue supergiant, and the dust it lights",
    family = "star",
    method = "computed",
    floor = 16.7,
    accents = 7,
    span = 198,
    chroma = 32.4,
    text_cr = 11.17,
    top_cr = 16.92,
    warm = 3,
  },
  {
    name = "observatory-deneb",
    about = "one line, in emission and in absorption",
    family = "star",
    method = "computed",
    floor = 13.9,
    accents = 7,
    span = 250,
    chroma = 49.3,
    text_cr = 11.56,
    top_cr = 16.94,
    warm = 3,
  },
  {
    name = "observatory-mira",
    about = "the first variable, and the band that exaggerates it",
    family = "star",
    method = "computed",
    floor = 22.6,
    accents = 7,
    span = 178,
    chroma = 41.8,
    text_cr = 10.34,
    top_cr = 16.82,
    warm = 5,
  },
  {
    name = "observatory-bluedwarf",
    about = "a red dwarf's whole future, in six steps",
    family = "star",
    method = "computed",
    floor = 19.0,
    accents = 7,
    span = 184,
    chroma = 34.8,
    text_cr = 12.84,
    top_cr = 16.25,
    warm = 5,
  },
  {
    name = "observatory-cooling",
    about = "a white dwarf, from 100,000 K down to nothing",
    family = "star",
    method = "computed",
    floor = 17.8,
    accents = 7,
    span = 171,
    chroma = 33.1,
    text_cr = 11.02,
    top_cr = 16.88,
    warm = 3,
  },
  {
    name = "observatory-blackdwarf",
    about = "the coldest thing there will ever be, and its last light",
    family = "star",
    method = "computed",
    floor = 21.5,
    accents = 6,
    span = 169,
    chroma = 44.8,
    text_cr = 11.75,
    top_cr = 15.94,
    warm = 5,
  },
  {
    name = "observatory-straggler",
    about = "one cluster's diagram, and the stars that break it",
    family = "star",
    method = "computed",
    floor = 17.8,
    accents = 7,
    span = 176,
    chroma = 27.3,
    text_cr = 10.78,
    top_cr = 16.85,
    warm = 3,
  },
  {
    name = "observatory-trappist",
    about = "bone-dry rock in the habitable zone of a red dwarf",
    family = "exo",
    method = "sampled",
    floor = 17.6,
    accents = 5,
    span = 174,
    chroma = 31.5,
    text_cr = 13.07,
    top_cr = 16.92,
    warm = 1,
  },
  {
    name = "observatory-trappist-computed",
    about = "seven worlds, and the one small red star lighting them",
    family = "exo",
    method = "computed",
    floor = 16.4,
    accents = 7,
    span = 2,
    chroma = 38.9,
    text_cr = 10.78,
    top_cr = 16.88,
    warm = 7,
  },
  {
    name = "observatory-tres2",
    about = "the darkest world known, and the dimmest palette here",
    family = "exo",
    method = "sampled",
    floor = 22.0,
    accents = 5,
    span = 17,
    chroma = 54.0,
    text_cr = 10.09,
    top_cr = 10.94,
    warm = 5,
  },
  {
    name = "observatory-hd189733",
    about = "the one exoplanet whose color was measured, and it is blue",
    family = "exo",
    method = "sampled",
    floor = 15.6,
    accents = 7,
    span = 23,
    chroma = 31.2,
    text_cr = 11.12,
    top_cr = 17.00,
    warm = 0,
  },
  {
    name = "observatory-eburonia",
    about = "a hot Neptune in violet and indigo, and its orange dwarf",
    family = "exo",
    method = "sampled",
    floor = 15.7,
    accents = 7,
    span = 159,
    chroma = 54.5,
    text_cr = 12.26,
    top_cr = 16.89,
    warm = 3,
  },
  {
    name = "observatory-kepler56c",
    about = "a red giant, and the planet it is about to swallow",
    family = "exo",
    method = "sampled",
    floor = 9.2,
    accents = 8,
    span = 69,
    chroma = 60.7,
    text_cr = 12.41,
    top_cr = 16.95,
    warm = 8,
  },
  {
    name = "observatory-kepler292b",
    about = "a super-Earth as an ocean world, in teal and sea green",
    family = "exo",
    method = "sampled",
    floor = 17.6,
    accents = 5,
    span = 30,
    chroma = 29.9,
    text_cr = 13.61,
    top_cr = 16.91,
    warm = 0,
  },
  {
    name = "observatory-kepler20b",
    about = "five planets ranged against Mercury's orbit",
    family = "exo",
    method = "sampled",
    floor = 17.2,
    accents = 8,
    span = 215,
    chroma = 36.8,
    text_cr = 12.62,
    top_cr = 16.92,
    warm = 4,
  },
  {
    name = "observatory-hd40307f",
    about = "gray super-Earths under an orange dwarf",
    family = "exo",
    method = "sampled",
    floor = 17.3,
    accents = 6,
    span = 174,
    chroma = 31.7,
    text_cr = 12.90,
    top_cr = 16.40,
    warm = 5,
  },
  {
    name = "observatory-kepler90h",
    about = "the eight-planet system, in olive and gold",
    family = "exo",
    method = "sampled",
    floor = 9.4,
    accents = 7,
    span = 25,
    chroma = 45.6,
    text_cr = 12.41,
    top_cr = 16.87,
    warm = 7,
  },
  {
    name = "observatory-mintome",
    about = "the pink planet: a giant still glowing from its own formation",
    family = "exo",
    method = "sampled",
    floor = 16.6,
    accents = 5,
    span = 78,
    chroma = 24.8,
    text_cr = 12.58,
    top_cr = 16.86,
    warm = 5,
  },
  {
    name = "observatory-hd157172b",
    about = "a hot Jupiter being eaten, and the star doing it",
    family = "exo",
    method = "sampled",
    floor = 16.7,
    accents = 6,
    span = 20,
    chroma = 53.4,
    text_cr = 12.66,
    top_cr = 15.04,
    warm = 5,
  },
  {
    name = "observatory-gliese3323b",
    about = "sage and slate, with one steel-blue sea",
    family = "exo",
    method = "sampled",
    floor = 16.7,
    accents = 6,
    span = 205,
    chroma = 37.4,
    text_cr = 13.19,
    top_cr = 15.61,
    warm = 2,
  },
  {
    name = "observatory-kepler1275b",
    about = "a frozen super-Earth in russet, at the edge of the light",
    family = "exo",
    method = "sampled",
    floor = 9.8,
    accents = 4,
    span = 31,
    chroma = 28.2,
    text_cr = 12.40,
    top_cr = 16.86,
    warm = 4,
  },
  {
    name = "observatory-kepler1328b",
    about = "a terrestrial placeholder in tan and umber",
    family = "exo",
    method = "sampled",
    floor = 17.6,
    accents = 4,
    span = 25,
    chroma = 33.4,
    text_cr = 13.61,
    top_cr = 16.90,
    warm = 4,
  },
  {
    name = "observatory-kepler438b",
    about = "a superflare sterilising a habitable-zone planet",
    family = "exo",
    method = "sampled",
    floor = 16.5,
    accents = 5,
    span = 26,
    chroma = 31.8,
    text_cr = 12.40,
    top_cr = 16.62,
    warm = 5,
  },
  {
    name = "observatory-kepler367b",
    about = "an atmosphere streaming off a small planet, in indigo and amber",
    family = "exo",
    method = "sampled",
    floor = 9.5,
    accents = 7,
    span = 132,
    chroma = 34.9,
    text_cr = 12.45,
    top_cr = 16.90,
    warm = 6,
  },
  {
    name = "observatory-sweeps10",
    about = "a Jupiter skimming a spotted red star, ten hours per year",
    family = "exo",
    method = "sampled",
    floor = 16.8,
    accents = 6,
    span = 42,
    chroma = 30.9,
    text_cr = 12.48,
    top_cr = 16.90,
    warm = 6,
  },
  {
    name = "observatory-enaiposha",
    about = "a steam world in silhouette against a red dwarf",
    family = "exo",
    method = "sampled",
    floor = 9.6,
    accents = 4,
    span = 150,
    chroma = 24.0,
    text_cr = 12.35,
    top_cr = 16.90,
    warm = 2,
  },
  {
    name = "observatory-dimidium",
    about = "the first planet found around a sun-like star, in tan and butterscotch",
    family = "exo",
    method = "sampled",
    floor = 9.8,
    accents = 4,
    span = 45,
    chroma = 24.5,
    text_cr = 12.40,
    top_cr = 16.95,
    warm = 4,
  },
  {
    name = "observatory-tatooine",
    about = "two suns, one silhouette, and every color warm",
    family = "exo",
    method = "sampled",
    floor = 9.4,
    accents = 5,
    span = 29,
    chroma = 47.9,
    text_cr = 12.42,
    top_cr = 16.93,
    warm = 5,
  },
  {
    name = "observatory-osiris",
    about = "a planet boiling away, gold against an ice-blue tail",
    family = "exo",
    method = "sampled",
    floor = 16.8,
    accents = 8,
    span = 181,
    chroma = 38.2,
    text_cr = 12.21,
    top_cr = 16.90,
    warm = 7,
  },
  {
    name = "observatory-methuselah",
    about = "the oldest planet known, in teal and cobalt",
    family = "exo",
    method = "sampled",
    floor = 17.4,
    accents = 6,
    span = 190,
    chroma = 26.4,
    text_cr = 12.36,
    top_cr = 16.74,
    warm = 2,
  },
  {
    name = "observatory-catseye",
    about = "concentric shells in lilac and slate, eleven of them",
    family = "nebula",
    method = "sampled",
    floor = 17.4,
    accents = 5,
    span = 136,
    chroma = 24.4,
    text_cr = 12.49,
    top_cr = 16.92,
    warm = 2,
  },
  {
    name = "observatory-catseye-computed",
    about = "a planetary nebula's shells, ordered by ionisation energy",
    family = "nebula",
    method = "computed",
    floor = 23.4,
    accents = 9,
    span = 288,
    chroma = 37.6,
    text_cr = 10.49,
    top_cr = 16.93,
    warm = 4,
  },
  {
    name = "observatory-crab",
    about = "a supernova's wreckage: teal synchrotron under gold filaments",
    family = "nebula",
    method = "sampled",
    floor = 9.5,
    accents = 8,
    span = 174,
    chroma = 31.3,
    text_cr = 12.41,
    top_cr = 16.91,
    warm = 2,
  },
  {
    name = "observatory-crab-computed",
    about = "synchrotron continuum against line filaments",
    family = "nebula",
    method = "computed",
    floor = 12.5,
    accents = 8,
    span = 216,
    chroma = 31.2,
    text_cr = 12.11,
    top_cr = 16.91,
    warm = 2,
  },
  {
    name = "observatory-helix",
    about = "the Eye of God: a rust iris around a periwinkle pupil",
    family = "nebula",
    method = "sampled",
    floor = 9.2,
    accents = 8,
    span = 187,
    chroma = 31.3,
    text_cr = 12.32,
    top_cr = 16.89,
    warm = 6,
  },
  {
    name = "observatory-helix-computed",
    about = "the Eye of God, and the ten thousand knots in it",
    family = "nebula",
    method = "computed",
    floor = 26.1,
    accents = 7,
    span = 221,
    chroma = 39.0,
    text_cr = 11.62,
    top_cr = 15.60,
    warm = 4,
  },
  {
    name = "observatory-trifid",
    about = "three dust lanes across pink hydrogen, and a blue reflection",
    family = "nebula",
    method = "sampled",
    floor = 15.2,
    accents = 6,
    span = 138,
    chroma = 26.5,
    text_cr = 11.71,
    top_cr = 16.94,
    warm = 4,
  },
  {
    name = "observatory-trifid-computed",
    about = "one star, and the three things dust does to its light",
    family = "nebula",
    method = "computed",
    floor = 17.2,
    accents = 7,
    span = 240,
    chroma = 41.7,
    text_cr = 13.82,
    top_cr = 13.91,
    warm = 3,
  },
  {
    name = "observatory-boomerang",
    about = "the coldest known place, and it photographs as warm gray",
    family = "nebula",
    method = "sampled",
    floor = 18.2,
    accents = 8,
    span = 102,
    chroma = 35.6,
    text_cr = 13.68,
    top_cr = 14.44,
    warm = 7,
  },
  {
    name = "observatory-boomerang-computed",
    about = "one kelvin, which has no color, so this is borrowed light",
    family = "nebula",
    method = "computed",
    floor = 15.3,
    accents = 6,
    span = 158,
    chroma = 36.7,
    text_cr = 11.13,
    top_cr = 16.94,
    warm = 2,
  },
  {
    name = "observatory-orion",
    about = "the sharpest view of the nebula, in brick and rose",
    family = "nebula",
    method = "sampled",
    floor = 16.2,
    accents = 6,
    span = 43,
    chroma = 36.0,
    text_cr = 11.79,
    top_cr = 16.89,
    warm = 6,
  },
  {
    name = "observatory-orion-computed",
    about = "one constellation, measured",
    family = "nebula",
    method = "computed",
    floor = 16.7,
    accents = 7,
    span = 234,
    chroma = 39.9,
    text_cr = 11.17,
    top_cr = 16.92,
    warm = 3,
  },
  {
    name = "observatory-bimodal",
    about = "galaxies come in two colors, and the gap is not green",
    family = "galaxy",
    method = "sampled",
    floor = 18.8,
    accents = 7,
    span = 152,
    chroma = 30.5,
    text_cr = 10.53,
    top_cr = 16.26,
    warm = 4,
  },
  {
    name = "observatory-hoag",
    about = "a gold core inside a detached ring, and nothing in between",
    family = "galaxy",
    method = "sampled",
    floor = 9.4,
    accents = 7,
    span = 217,
    chroma = 36.6,
    text_cr = 12.44,
    top_cr = 16.93,
    warm = 5,
  },
  {
    name = "observatory-hoag-computed",
    about = "an old core, a young ring, and nothing in between",
    family = "galaxy",
    method = "computed",
    floor = 15.6,
    accents = 7,
    span = 166,
    chroma = 28.6,
    text_cr = 11.44,
    top_cr = 16.89,
    warm = 4,
  },
  {
    name = "observatory-voorwerp",
    about = "a green ghost lit by a quasar that has already gone out",
    family = "galaxy",
    method = "sampled",
    floor = 17.7,
    accents = 5,
    span = 145,
    chroma = 34.1,
    text_cr = 13.58,
    top_cr = 16.90,
    warm = 4,
  },
  {
    name = "observatory-voorwerp-computed",
    about = "the one green thing, and it is gas rather than a star",
    family = "galaxy",
    method = "computed",
    floor = 27.3,
    accents = 7,
    span = 262,
    chroma = 42.9,
    text_cr = 13.19,
    top_cr = 15.41,
    warm = 3,
  },
  {
    name = "observatory-galaxy",
    about = "color as age, across a spiral galaxy",
    family = "galaxy",
    method = "sampled",
    floor = 17.0,
    accents = 7,
    span = 171,
    chroma = 28.6,
    text_cr = 10.63,
    top_cr = 17.01,
    warm = 4,
  },
  {
    name = "observatory-milkyway",
    about = "our own galaxy from outside, which nobody has seen",
    family = "galaxy",
    method = "sampled",
    floor = 16.4,
    accents = 4,
    span = 183,
    chroma = 24.6,
    text_cr = 12.52,
    top_cr = 16.93,
    warm = 1,
  },
  {
    name = "observatory-milkyway-computed",
    about = "our own galaxy, whose color was the hardest to measure",
    family = "galaxy",
    method = "computed",
    floor = 15.9,
    accents = 7,
    span = 151,
    chroma = 28.8,
    text_cr = 13.65,
    top_cr = 15.92,
    warm = 4,
  },
  {
    name = "observatory-milkywayparanal",
    about = "the galactic plane over Paranal, in slate and mauve",
    family = "galaxy",
    method = "sampled",
    floor = 12.6,
    accents = 4,
    span = 60,
    chroma = 7.4,
    text_cr = 10.03,
    top_cr = 16.93,
    warm = 4,
  },
  {
    name = "observatory-deepfield",
    about = "ten thousand galaxies, and four per cent of the frame is lit",
    family = "galaxy",
    method = "sampled",
    floor = 9.4,
    accents = 7,
    span = 223,
    chroma = 27.3,
    text_cr = 12.43,
    top_cr = 16.88,
    warm = 5,
  },
  {
    name = "observatory-deepfield-computed",
    about = "ten thousand galaxies, sorted by how long the light took",
    family = "galaxy",
    method = "computed",
    floor = 27.3,
    accents = 6,
    span = 210,
    chroma = 53.8,
    text_cr = 11.60,
    top_cr = 16.50,
    warm = 4,
  },
  {
    name = "observatory-deepfieldwebb",
    about = "the first Webb deep field, in amber and steel",
    family = "galaxy",
    method = "sampled",
    floor = 15.8,
    accents = 6,
    span = 167,
    chroma = 36.3,
    text_cr = 11.18,
    top_cr = 16.85,
    warm = 5,
  },
  {
    name = "observatory-eventhorizon",
    about = "the first photograph of a black hole, and it is all one hue",
    family = "event",
    method = "sampled",
    floor = 16.3,
    accents = 7,
    span = 40,
    chroma = 50.1,
    text_cr = 12.45,
    top_cr = 16.99,
    warm = 7,
  },
  {
    name = "observatory-eventhorizon-computed",
    about = "the colormap the black hole pictures used",
    family = "event",
    method = "computed",
    floor = 16.9,
    accents = 8,
    span = 58,
    chroma = 50.4,
    text_cr = 11.19,
    top_cr = 17.00,
    warm = 8,
  },
  {
    name = "observatory-jet",
    about = "the same hole four years later, in violet, with its jet",
    family = "event",
    method = "sampled",
    floor = 9.3,
    accents = 8,
    span = 132,
    chroma = 45.6,
    text_cr = 12.38,
    top_cr = 16.88,
    warm = 7,
  },
  {
    name = "observatory-shadow",
    about = "the black hole picture as recorded, which is gray",
    family = "event",
    method = "sampled",
    floor = 11.3,
    accents = 3,
    span = 0,
    chroma = 0.0,
    text_cr = 12.81,
    top_cr = 17.94,
    warm = 0,
  },
  {
    name = "observatory-cosmicbackground",
    about = "the oldest light there is, as a temperature map",
    family = "event",
    method = "sampled",
    floor = 17.7,
    accents = 8,
    span = 178,
    chroma = 40.5,
    text_cr = 13.61,
    top_cr = 16.93,
    warm = 3,
  },
  {
    name = "observatory-cosmicbackground-computed",
    about = "a diverging scale, cold to hot, like the anisotropy maps",
    family = "event",
    method = "computed",
    floor = 11.0,
    accents = 8,
    span = 201,
    chroma = 35.8,
    text_cr = 15.35,
    top_cr = 13.21,
    warm = 3,
  },
  {
    name = "observatory-cosmicbackgroundlegacy",
    about = "the last word on the oldest light, in eight colors",
    family = "event",
    method = "sampled",
    floor = 17.3,
    accents = 8,
    span = 170,
    chroma = 44.3,
    text_cr = 12.45,
    top_cr = 16.90,
    warm = 5,
  },
  {
    name = "observatory-kilonova",
    about = "two neutron stars merging, and where the gold came from",
    family = "event",
    method = "sampled",
    floor = 17.1,
    accents = 7,
    span = 185,
    chroma = 32.0,
    text_cr = 12.25,
    top_cr = 16.86,
    warm = 1,
  },
  {
    name = "observatory-kilonova-computed",
    about = "a photosphere crossing the whole stellar locus in five days",
    family = "event",
    method = "computed",
    floor = 13.6,
    accents = 6,
    span = 171,
    chroma = 27.7,
    text_cr = 12.36,
    top_cr = 16.91,
    warm = 4,
  },
  {
    name = "observatory-supernova1987a",
    about = "the nearest supernova in four centuries, ringed",
    family = "event",
    method = "sampled",
    floor = 17.8,
    accents = 5,
    span = 195,
    chroma = 32.0,
    text_cr = 13.45,
    top_cr = 16.94,
    warm = 3,
  },
  {
    name = "observatory-cassiopeia",
    about = "a remnant in X-rays, which makes it violet",
    family = "event",
    method = "sampled",
    floor = 17.9,
    accents = 8,
    span = 234,
    chroma = 33.5,
    text_cr = 13.64,
    top_cr = 15.46,
    warm = 3,
  },
  {
    name = "observatory-cassiopeiawebb",
    about = "the same remnant in the infrared, which makes it teal and rust",
    family = "event",
    method = "sampled",
    floor = 9.5,
    accents = 8,
    span = 207,
    chroma = 30.0,
    text_cr = 12.47,
    top_cr = 16.89,
    warm = 6,
  },
  {
    name = "observatory-tycho",
    about = "the star that proved the heavens change, in crimson and periwinkle",
    family = "event",
    method = "sampled",
    floor = 16.9,
    accents = 8,
    span = 96,
    chroma = 33.6,
    text_cr = 13.19,
    top_cr = 16.98,
    warm = 6,
  },
  {
    name = "observatory-nova",
    about = "a white dwarf's surface igniting, hour by week",
    family = "event",
    method = "computed",
    floor = 17.8,
    accents = 8,
    span = 233,
    chroma = 35.6,
    text_cr = 12.78,
    top_cr = 16.92,
    warm = 3,
  },
  {
    name = "observatory-brightestofalltime",
    about = "the brightest burst ever recorded, in dust echoes",
    family = "event",
    method = "sampled",
    floor = 9.7,
    accents = 6,
    span = 40,
    chroma = 48.7,
    text_cr = 12.39,
    top_cr = 16.90,
    warm = 6,
  },
  {
    name = "observatory-balmer",
    about = "the hydrogen Balmer series, brightness following line strength",
    family = "reading",
    method = "computed",
    floor = 10.8,
    accents = 7,
    span = 176,
    chroma = 44.7,
    text_cr = 15.31,
    top_cr = 12.60,
    warm = 1,
  },
  {
    name = "observatory-doppler",
    about = "one spectral line, seven velocities",
    family = "reading",
    method = "computed",
    floor = 10.6,
    accents = 8,
    span = 265,
    chroma = 44.0,
    text_cr = 15.45,
    top_cr = 14.40,
    warm = 2,
  },
  {
    name = "observatory-pulsar",
    about = "maximum contrast, and pale because of it",
    family = "reading",
    method = "computed",
    floor = 10.3,
    accents = 7,
    span = 224,
    chroma = 26.1,
    text_cr = 19.40,
    top_cr = 17.58,
    warm = 2,
  },
  {
    name = "observatory-fraunhofer",
    about = "the Sun's own labelled absorption lines",
    family = "reading",
    method = "computed",
    floor = 29.7,
    accents = 10,
    span = 286,
    chroma = 54.0,
    text_cr = 12.79,
    top_cr = 13.35,
    warm = 4,
  },
  {
    name = "observatory-meteor",
    about = "what the rock was made of, while it lasted",
    family = "reading",
    method = "computed",
    floor = 30.4,
    accents = 8,
    span = 207,
    chroma = 51.9,
    text_cr = 13.47,
    top_cr = 16.86,
    warm = 3,
  },
  {
    name = "observatory-hertzsprungrussell",
    about = "a color-magnitude diagram, both axes used",
    family = "reading",
    method = "computed",
    floor = 17.5,
    accents = 7,
    span = 172,
    chroma = 26.1,
    text_cr = 10.68,
    top_cr = 16.94,
    warm = 4,
  },
  {
    name = "observatory-extinction",
    about = "one blue star behind seven columns of dust",
    family = "reading",
    method = "computed",
    floor = 15.5,
    accents = 7,
    span = 171,
    chroma = 32.8,
    text_cr = 10.55,
    top_cr = 16.90,
    warm = 5,
  },
  {
    name = "observatory-kuiper",
    about = "two populations, and the gap between them",
    family = "reading",
    method = "computed",
    floor = 16.8,
    accents = 8,
    span = 15,
    chroma = 45.1,
    text_cr = 11.19,
    top_cr = 16.97,
    warm = 8,
  },
  {
    name = "observatory-plate",
    about = "no color at all, and the five grays that leaves",
    family = "reading",
    method = "computed",
    floor = 12.2,
    accents = 4,
    span = 0,
    chroma = 0.0,
    text_cr = 15.31,
    top_cr = 21.00,
    warm = 0,
  },
  {
    name = "observatory-albedo",
    about = "the solar system, lit by apparent magnitude",
    family = "construction",
    method = "solved",
    floor = 10.8,
    accents = 8,
    span = 201,
    chroma = 28.2,
    text_cr = 12.21,
    top_cr = 15.83,
    warm = 6,
  },
  {
    name = "observatory-dichroic",
    about = "legible with red-green and blue-yellow color blindness",
    family = "construction",
    method = "solved",
    floor = 14.2,
    accents = 7,
    span = 248,
    chroma = 38.1,
    text_cr = 15.42,
    top_cr = 12.58,
    warm = 4,
  },
  {
    name = "observatory-horizon",
    about = "one line falling into a black hole",
    family = "construction",
    method = "solved",
    floor = 10.5,
    accents = 9,
    span = 267,
    chroma = 39.5,
    text_cr = 15.42,
    top_cr = 13.43,
    warm = 2,
  },
  {
    name = "observatory-lagrange",
    about = "the palette solved for maximum separation",
    family = "construction",
    method = "solved",
    floor = 19.1,
    accents = 10,
    span = 270,
    chroma = 51.2,
    text_cr = 15.42,
    top_cr = 12.68,
    warm = 3,
  },
  {
    name = "observatory-phi",
    about = "hues at the golden angle, so any subset stays spread",
    family = "construction",
    method = "solved",
    floor = 20.4,
    accents = 10,
    span = 296,
    chroma = 50.9,
    text_cr = 15.42,
    top_cr = 12.66,
    warm = 4,
  },
  {
    name = "observatory-syzygy",
    about = "separation spent where tokens actually touch",
    family = "construction",
    method = "solved",
    floor = 15.5,
    accents = 10,
    span = 304,
    chroma = 50.4,
    text_cr = 15.42,
    top_cr = 12.51,
    warm = 3,
  },
}
